Repository cloudfoundry/docs-bbr, pull requests merged in 2018-04, with the labels that each got.

#27 Add note about custom certs to the external blobstores page
  external-blobstores.html.md.erb
Labels: scheduled

#28 Document --artifact-path for backups
  index.html.md.erb
Labels: scheduled

#29 Correct anchor link to good-practices
  backup.html.md.erb
Labels: scheduled

#30 Update bbr-rn.html.md.erb
  bbr-rn.html.md.erb
Labels: unscheduled

#31 new release 1.2.2
  bbr-rn.html.md.erb
Labels: in progress
